apiVersion: apps/v1
kind: Deployment
metadata:
  name: praveen-devops-page
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: praveen-devops-page
  template:
    metadata:
      labels:
        app: praveen-devops-page
    spec:
      containers:
      - name: praveen-devops-page
        image: praveen1351/devops-page:df7cde8652a91fa15742dd9de1575baf20aba9a9
        ports:
        - containerPort: 80
