apiVersion: apps/v1
kind: Deployment
metadata:
  name: praveen-devops-page
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: praveen-devops-page
  template:
    metadata:
      labels:
        app: praveen-devops-page
    spec:
      containers:
      - name: praveen-devops-page
        image: praveen1351/devops-page:0f8f3aaf0e271328dd260c51aec703f4c0e691e8
        ports:
        - containerPort: 80
