apiVersion: v1
kind: Service
metadata:
  name: praveen-devops-page-service
  namespace: qa
spec:
  selector:
    app: praveen-devops-page
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
